### ISSUE TITLE
Sustain pedal not "sustaining" notes

### ISSUE THREAD

**Issue by ffont** [ffont/ddrm-issues#1]
Sustain pedal does not seem to be working. Tried with both Sustain I and Sustain II modes and makes no difference. Can anyone confirm whether sustain pedal works for you?

**Comment by ffont** [comment]
It has been said in the Facebook DD Build group that sustain pedal works but needs to be enabled in settings by turning on "MIDI cc receive". I have not tested it yet. Will update once I have tested it.

**Comment by MrPandoman** [comment]
Yes, MIDI CC Receive needs to be ON in settings before the sustain slider (or any CC# messages) will work. There is a MIDI implementation chart published in the Facebook Build group in the files section.

**Comment by ffont** [comment]
Thanks @MrPandoman, turning on MIDI CC receive solves this issue as well as #3.
