### ISSUE TITLE
v1.2.1 in MPE mode, pitch bend range is stuck at 48, no matter what number is set in Keyboard -> Pitch Bend Range. Makes Linnstrument slides wrong pitches

### ISSUE THREAD

**Issue by schillp5** [ffont/ddrm-issues#15]
In Channel AT and Poly AT modes, Keyboard -> Pitch Bend Range setting correctly sets the pitch bend range, but is ignored in MPE mode. The result is when played on Linnstrument, the slides don't end up with the correct pitch because the maximum pitch bend range setting on Linnstrument is 24...

**Comment by schillp5** [comment]
this is a lower priority for me because I found the hidden way to set the Linnstrument to 48 semitones pitch bend range

**Comment by ffont** [comment]
@schillp5 regardless of the priority, if this is an issue that should be fixed sooner or later I'd re-open this issue.
