### ISSUE TITLE
v1.2.X VCO jittering glitch

### ISSUE THREAD

**Issue by ffont** [ffont/ddrm-issues#20]
As reported by some users in the FB group.
The same jittering problems described in #2 and #5 in some cases also affect VCOs with much more audible effects than in the other cases. See the following description of the issue posted in FB group:

> REV1.0 is OK
> REV1.2.x all have VCO jitter
> 
> What it sounds like? See the videos I've posted earlier, like this one: https://www.facebook.com/IsotaloJanne/videos/10156321598774293/
> 
> I've found this to be most hearable with "dull" sounds like bank2 - 09 from the 1.2.3 soundbank file.
> 
> EDIT: For all the DDRM users interested in whether their unit have these same kind of issues or not, try this:
> 
> Setting - Calibration - debug and press next repeatidly until you get to the "pitch coarse". In the middle area of the slider this jitter should be most noticable. Display should show numbers switching between two values even when you don't move the slider. In the end of the slider this action should be milder.
> 
> If using REV1.0 firmware, while moving the "pitch coarse" in debug mode numbers should change in 8 increments and since the jittering was only in 2 increments, this REV1.0 doesn't have this VCO jitter problem at all.
> 
> If using REV1.2.x firmware, and not hearing any vco jitter, it's still there, you just need to move the "pitch coarse" slider just a tiny bit and you'll get it hearable again.

Apparently slider jitter is not a problem in REV2 DDRM because sliders have their own stable 3.3V power rail which is not affected by noise coming from ICs. There is a long discussion in the FB talking about potential hardware-based solutions but no relevant conclusions yet. Nevertheless, this problem should be solvable via firmware.

**Comment by schillp5** [comment]
In the upcoming version (1.2.4), the VCO jitter has been minimized by introducing hysteresis/lag to the slide reading. The jitter is now confined to jumps of 2, occurs less frequently and in a more limited slider range (approximately between 100 and 125, which is below the center)

**Comment by schillp5** [comment]
In the upcoming version (1.2.4), the VCO jitter has been eliminated by 1. introducing hysteresis/lag to the slider reading, and 2. going back to the v1.0 behavior where the Coarse Pitch slider values are jumping in larger increments.  This results in the "jitter" never eclipsing the slider value increments. Also, no audible frequency stepping when sliding the Coarse Pitch slider. This was done only for Coarse Pitch - applying this change to VCF cutoff would result in undesirable audible VCF cutoff stepping while sliding the cutoff sliders

**Comment by ffont** [comment]
Closing as this was fixed in later firmware versions.
