### ISSUE TITLE
1.2.4 Mix1/2 bleed

### ISSUE THREAD

**Issue by ForDeckard** [ffont/ddrm-issues#21]
When the mix slider is either all the way up or down the other row is clearly audible. This is not the case in 1.2.3

**Comment by ffont** [comment]
There is in need some bleed through between channels but is is very very low. I have not tested rolling 1.2.3 back again though.

**Comment by ForDeckard** [comment]
In my case it's nowhere very very low. The difference between slider full up and full down is only 30 db. So it's clearly audible for sure. In 1.2.4 it's about 49. (If you know db, you will realise how big a 19 db difference is). BUT in 1.2.3 the slider behaviour it is rocky however. Sometimes it does bleed like in 1.2.4 and it seems it's the slider that does not go far enough and what also happens is there is a big step/drop in volume in the maximum setting. Look at the movie:

https://www.dropbox.com/s/ubi1qr4mwp52wyc/Mix%20Slider%20volume%20drop.MOV?dl=0

All pretty unpredictable.

**Comment by ffont** [comment]
Closing as this was improved in further firmware versions.
