### ISSUE TITLE
USB hum

### ISSUE THREAD

**Issue by ForDeckard** [ffont/ddrm-issues#23]
when the usb is connected there is a loud noise/hum audible. In multiple firmware (1.2.3, 1.2.4)

**Comment by ffont** [comment]
I guess this is something that can’t be helped via firmware... but what about a mod which puts the audio output jack somewhere else? @MrPandoman

**Comment by ForDeckard** [comment]
I have a prebuilt dd, can that mod be made?

**Comment by ffont** [comment]
I don’t know if such a mod is possible and would fix the issue, just wondering about that and pinging mrpandoman as he’s the expert. Might be worth posting this to the build group...

**Comment by ForDeckard** [comment]
Got some help on te Fb page. I probably have a ground loop. I bought an ART DTI Isolator and that fixed the issue.

**Comment by ffont** [comment]
Great to hear, I'll close the issue then!
