### ISSUE TITLE
1.2.4 Sine slider dead spot

### ISSUE THREAD

**Issue by ForDeckard** [ffont/ddrm-issues#24]
There is a dead spot in the sine slider in 1.2.4. You have to play around with the VCF level slider next to it and then suddenly there is no sine anymore with the sine slider on the top. 1.2.3 does not have this.

**Comment by ffont** [comment]
Running 1.2.4 I have not been able to reproduce this issue. Do you still experiment it?

**Comment by ForDeckard** [comment]
It does not seem to occur anymore in 1.2.4.

**Comment by ffont** [comment]
I’ll then close this issue for now. Thanks!
