### ISSUE TITLE
1.2.3 VCA level slider of Row 2 affects Sub oscillator speed

### ISSUE THREAD

**Issue by ForDeckard** [ffont/ddrm-issues#25]
See comment. If i e.g. set the Sub oscillator full to VCF (green slider down)  and the speed at 2/3 the way down, the speed gets faster when i lower the VCA level of row 2
https://www.dropbox.com/s/7lwj7evxg5mv2s5/Video%2016-05-18%2011%2013%2039.mov?dl=0

**Comment by ffont** [comment]
I tried to reproduce this and at some point I think I managed to do it but the change was lower than the one in the video. Then I was not able to do it again but I'm really not sure anymore now. Are you able to reproduce this consistently?

**Comment by ForDeckard** [comment]
Yes it's consistent

**Comment by schillp5** [comment]
Please install the new 1.2.7 firmware - it includes SubOsc slowdown fix

**Comment by ffont** [comment]
Closing as this was fixed in further firmware versions.
