### ISSUE TITLE
All Notes Off message is not recognised

### ISSUE THREAD

**Issue by c0ff** [ffont/ddrm-issues#27]
Please, implement All Notes Off message.

**Comment by schillp5** [comment]
Please when entering a bug like this, give detailed instructions on how to reproduce the bug. I would like to check this but don't know how to "send all notes off"

**Comment by schillp5** [comment]
This should be fixed now in v1.2.7 (all notes off = CC123)

**Comment by c0ff** [comment]
Indeed it is fixed in 1.2.7
