### ISSUE TITLE
Initial Level sliders not working?

### ISSUE THREAD

**Issue by ForDeckard** [ffont/ddrm-issues#29]
I know the IL and AL can be confusing for someone used to standard ADSR. I know it is to me. But i think my IL slider does not do anything. How can i test if it is working? (the debugger shows full movement). It should lower the initial level that the filter starts right? It does not seem to change anything.

**Comment by ffont** [comment]
As you mention IL and AL are typically confusing sliders in DDRM/CS80. There has been some discussion on the FB group now so I'm posting the permalink here for people who is also part of the group: https://www.facebook.com/groups/547920848891200/permalink/634323043584313/

For others, there should be a DDRM manual soon explaining how these things work (and also the CS80 manual is useful). Closing the issue as this is not an issue with the synth.
