### ISSUE TITLE
DD does not change present in response to MIDI Program Change messages

### ISSUE THREAD

**Issue by ffont** [ffont/ddrm-issues#3]
My DD unit does not change presents in response to MIDI program change messages. Did anyone succeed in getting this to work?

**Comment by MrPandoman** [comment]
This worked fine on the previous beta firmware. I have not tested it on 1.2.0, but you will need to turn on CC receive for any MIDI CC to work. This is in Settings > MIDI.

**Comment by ffont** [comment]
Solved by turning MIDI CC receive on.
