### ISSUE TITLE
Switching buttons send many MIDI CC messages

### ISSUE THREAD

**Issue by ffont** [ffont/ddrm-issues#32]
When switching the SQUARE on/off or SAW on/off buttons in any of the two channels, instead of sending a single MIDI Control Change message out with either 0 or 127 values, the DDRM sends 127 messages with all values from 0 to 127 or from 127 to 0 (depending on whether button is being switched from ON to OFF or from OFF to ON).

**Comment by schillp5** [comment]
My testing shows this is fixed in the new 1.2.7 version.

**Comment by ffont** [comment]
yeah my tests also show this works fine now!
