### ISSUE TITLE
GLIDE MODE uses reserved MICI CC #120

### ISSUE THREAD

**Issue by ffont** [ffont/ddrm-issues#33]
GLIDE MODE parameter uses MIDI Control Change #120. This value should not be used as the MIDI specification reserves it for RPN messages (Registered Parameter Number). This can become an issue for some MIDI controllers that take the specification very seriously and disallow the use of MIDI CC 120.

**Comment by ffont** [comment]
Looking at DDRM MIDI chart, values below CC#40 are not used (except for CC#5 and CC#8). Moving Glide slider to, for example, CC#14 should be fine as it is not reserved number.

**Comment by schillp5** [comment]
This has been changed to CC 39

**Comment by ffont** [comment]
Confirmed this has been changed to CC#39 on 1.2.7. Closing this issue.
