### ISSUE TITLE
PWM speed slider for channel II does not work

### ISSUE THREAD

**Issue by ffont** [ffont/ddrm-issues#4]
I have noticed that the PWM speed slider for channel II (first slider of second row) has no effect on PWM for channel II (does not behave like PWM speed in channel I). Instead, the PWM speed slider for channel I has effect on both channels (changing PWM speed in channel I affects PWM speed in channel II). Can anyone reproduce that?

If I go into debug mode and check the sliders individually, these work good and show correct values.

**Comment by MrPandoman** [comment]
This is because the PWM Sync is ON by default after upgrading to 1.2.0 firmware. Go to Settings > Time and turn off PWM SYNC.  (That said, this setting should really be OFF by default after upgrading).
