### ISSUE TITLE
Voice Card issue - No sound from voice I (1)

### ISSUE THREAD

**Issue by vincemickman** [ffont/ddrm-issues#7]
Firstly a little disclaimer; I am a newb with electronics so please excuse my lack of knowledge and for the mistakes I have made!

I thought everything was working OK with my DDRM but now that I've had a chance to put it through it's paces I notice that I have an issue with two of the voice cards. The issues are different so I have made one post for each, hope this is OK.

I have checked the boards in isolation and the issue I am having with this board is that I don't get any sound from voice I; no Saw, Triangle or Sub/Sine. Voice II is working fine.

I suspect the issue stems from me installing a TL061 backwards on this card (I can't remember exactly which one but think it was either IC7 or IC2). When I initially powered it up the chip popped and smoked. I have replaced it with a spare that I had but this hasn't fixed the issue which leads me to believe that I have blown something else on the board.  I had also missed a resister off the board (R93) but have now installed one but still no joy.

If anybody could point me in the right direction as to where to start trouble shooting that'd be fantastic!

**Comment by vincemickman** [comment]
Quick update: After testing some of the components with a transistor tester I've noticed that Q4 (2N3904) is showing as a 31pf capacitor when I connect leg 1 and leg 3 to the tester. All of the 2N3904 at Q4 on my working boards show as a diode when I connect leg 1 and leg 3 to the tester. I've been told that testing parts in circuit is not best practice but I'm wondering if replacing the 2N3904 at Q4 is a good place to start?

**Comment by MrPandoman** [comment]
Q4 only affects sine wave output, and on #2 voice only. It has no effect on the rest of the waveforms, or to anything on #1 voice. 31pF is such a low value that you're probably reading some of the capacitance on the PCB.

This component cannot cause the issue you're describing. If you smoked IC2, it probably affected the CEM chip IC1. If it was IC7, it probably affected the SSM2164 chip IC9. Swap these chips around from a good voice card and you'll probably find the bad one.

**Comment by vincemickman** [comment]
Thanks for taking the time to reply! Without it I wouldn't have had the confidence to try swapping chips around as I'm pretty scared of breaking things (I have form in this area)
After switching chips one by one and testing it turns out IC15 (V2164D SSM clone) was busted! I've installed a spare and the card is now fully operational!
