### ISSUE TITLE
Voice Card issue - No Saw or Tri from Voice I (1)

### ISSUE THREAD

**Issue by vincemickman** [ffont/ddrm-issues#8]
This is the second issue I am having with one of my voice cards.

With this card I am not getting any Saw or Tri from Voice I (1). The Sub/Sine wave works. Everything with Voice II (2) works fine.

I've looked over this board and can't find any errors like chips being installed backwards or missing resistors (not like me!)

Voice I does not produce the Saw and Tri waves but the Sub/Sine is coming through OK.  I've had a look over the schematics but I'm afraid they are well outside of my realm of comprehension so was wondering if somebody would be kind enough to point me in the right direction as to where to start trouble shooting.

**Comment by vincemickman** [comment]
Turns out the culprit was a faulty IC8 (TL062CP) so this one is solved now too.

**Comment by ffont** [comment]
Thanks! marking it as solved.
